language: cpp
compiler: clang
sudo: false
dist: trusty
script:
  - mkdir build
  - cd build
  - cmake ..
  - make
addons:
  apt:
    packages:
      - cmake
      - libxrandr-dev
      - libxinerama-dev
      - libxcursor-dev
      - libxi-dev